mockk/mockk

- mockk/src/main/kotlin/io/mockk/impl/instantiation/JvmMockFactoryHelper.kt
- mockk/src/main/kotlin/io/mockk/impl/recording/JvmAutoHinter.kt
- mockk/src/test/kotlin/io/mockk/impl/instantiation/JvmMockFactoryHelperTest.kt
It took only 2 small changes to bring JDK7 compatibility back. At least functionality that I'm currently using is working perfectly now.
> fix JDK7 compatibility (#43)

- common/src/main/kotlin/io/mockk/impl/annotations/InjectMockKs.kt
- common/src/main/kotlin/io/mockk/impl/annotations/SpyK.kt
- common/src/test/kotlin/io/mockk/it/AnnotationsTest.kt
- mockk/src/main/kotlin/io/mockk/impl/annotations/InjectionHelpers.kt
- mockk/src/main/kotlin/io/mockk/impl/annotations/JvmMockInitializer.kt
- mockk/src/main/kotlin/io/mockk/impl/annotations/MockInjector.kt
- mockk/src/test/kotlin/io/mockk/impl/annotations/MockInjectorTest.kt
Changes to support InjectMockKs and OverrideMockKs annotations
> Mock injection

- common/build.gradle
- common/src/main/kotlin/io/mockk/MockK.kt
- common/src/sample/kotlin/io/mockk/MockKSamples.kt
Added samples to documentation. This will enable that when users do CTRL +Q in Intellij, a sample will appear for them with some documentation. This minimizes confusion about how the lib works, and minimizes need for users to alt+tab all the time for some trivial implementation.
This documentation can be improved even further, but this is a proof of concept on how it should be done
> Improved documentation a little bit.

- agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/ObjenesisInstantiator.kt
- agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/transformation/SubclassInstrumentation.kt
- agent/jvm/src/test/java/io/mockk/proxy/JvmMockKProxyMakerTest.java
> Copy annotations from original class during bytebuddy

- mockk/src/main/kotlin/io/mockk/impl/JvmMockKGateway.kt
> Fix typo in JvmMockKGateway.kt

- README.md
I wrote a series of articles about MockK in Chinese (中文).
Hope it will help.
> Add Chinese MockK articles

- README.md
Fixed less() and more() usage example at README DSL tables.
> Fixed code example to match description

- ANDROID.md
> Typos on ANDROID.md

- README.md
> don't call .captured() on a list

- README.md
This PR fixes some typos and polishes the content of the README file.
> Fix typos and polish text

- README.md
Kotlin 1.3+ and Coroutines 1.0+ Version -> 1.10.0
Kotlin 1.2 Compatible Version -> 1.9.3
> docs: installation version is incorrect

- mockk/common/src/test/kotlin/io/mockk/it/AnnotationsTest.kt
- mockk/jvm/src/main/kotlin/io/mockk/impl/annotations/JvmMockInitializer.kt
Implemented the feature discussed in the issue below.
https://github.com/mockk/mockk/issues/315
> Issue 315: Allow to combine @SpyK with @InjectMockKs

- dsl/common/src/main/kotlin/io/mockk/API.kt
- mockk/common/src/test/kotlin/io/mockk/gh/Issue343Test.kt
* Added an overload for AndThenAnswer that has the functionality of AndThen.
* Deprecated  AndThen.
> Fix: 343 Added overload for AndThenAnswer.

- .github/workflows/gradle.yml
I had some issues getting tests to run on my local machine so I set up a Github action.
Maybe you're interested in using this in upstream - might need some additional tweaking as this is basically just the default configuration.
> ci: build project using Github actions

- mockk/jvm/src/test/kotlin/io/mockk/it/JavaClassParamTest.kt
- mockk/jvm/src/test/kotlin/io/mockk/it/LocaleTest.kt
I tried with two issues (29 and 94). I hope is what you ask for. In case i could continue to reorganize remaining issues.
> Reorganize tests

- README.md
Add a section about calling the original method. #436.
> Document real partial mock

- settings.gradle.kts
Initial commit for #690 that migrates settings.gradle to settings.gradle.kts.
> Migrate settings.gradle to kts

- gradle/wrapper/gradle-wrapper.properties
https://docs.gradle.org/7.3.2/release-notes.html
> Gradle upgrade to 7.3.2

- build.gradle
- client-tests/jvm/build.gradle.kts
- plugins/dependencies/src/main/kotlin/io/mockk/dependencies/Deps.kt
Bumping a few versions, to avoid versions conflicts for users.
> Bump dependencies versions

- plugins/dependencies/src/main/kotlin/io/mockk/dependencies/Deps.kt
https://logback.qos.ch/news.html
> Update logback to 1.2.10

- mockk/common/src/main/kotlin/io/mockk/impl/verify/UnorderedCallVerifier.kt
- mockk/common/src/test/kotlin/io/mockk/it/VerifyAtLeastAtMostExactlyTest.kt
fix #806
atLeast = 0 doesn't work
> Recognize atLeast = 0

- dsl/common/src/main/kotlin/io/mockk/Matchers.kt
> Revert "Added logging when matcher fails with an assertion error"

- .github/workflows/gradle.yml
- buildSrc/src/main/kotlin/buildsrc/config/Deps.kt
- buildSrc/src/main/kotlin/buildsrc/convention/android-application.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/android-library.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/kotlin-jvm.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/kotlin-multiplatform.gradle.kts
> Standardise JVM target to be 1.8

- buildSrc/src/main/kotlin/buildsrc/convention/kotlin-multiplatform.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/toolchain-jvm.gradle.kts
> make Java source code target jvm 8

- .github/workflows/gradle.yml
> add jdk 19 to workflow test matrix

- jitpack.yml
Allows to use jitpack.io for snapshot usage in real-world projects
> added basic jitpack config

- .github/workflows/gradle.yml
Add kotlin 1.8-Beta to the test matrix.
Also update Kotlin 1.7.20 -> 1.7.21
> add kotlin 1.8-Beta to the test matrix

- buildSrc/src/main/kotlin/buildsrc/config/Deps.kt
> Update ByteBuddy to 1.12.20

- modules/mockk-agent-api/src/jvmMain/kotlin/io/mockk/proxy/common/transformation/ClassTransformationSpecMap.kt
- modules/mockk-agent/src/jvmMain/kotlin/io/mockk/proxy/jvm/ObjenesisInstantiator.kt
- modules/mockk-agent/src/jvmMain/kotlin/io/mockk/proxy/jvm/advice/SelfCallEliminator.kt
- modules/mockk-agent/src/jvmMain/kotlin/io/mockk/proxy/jvm/dispatcher/BootJarLoader.kt
- modules/mockk-dsl/src/jvmMain/kotlin/io/mockk/MockKSettings.kt
- modules/mockk/src/jvmMain/kotlin/io/mockk/impl/InternalPlatform.kt
- modules/mockk/src/jvmMain/kotlin/io/mockk/impl/JvmMockKGateway.kt
- modules/mockk/src/jvmMain/kotlin/io/mockk/impl/instantiation/JvmConstructorMockFactory.kt
- modules/mockk/src/jvmMain/kotlin/io/mockk/impl/instantiation/RefCounterMap.kt
- modules/mockk/src/jvmMain/kotlin/io/mockk/impl/recording/JvmSignatureValueGenerator.kt
java.util.* is a wildcard import. Replaced with fully qualified imports
> Replaced with fully qualified imports

- test-modules/client-tests/src/jvmTest/kotlin/io/mockk/core/ValueClassSupportTest.kt
- test-modules/client-tests/src/jvmTest/kotlin/io/mockk/impl/log/JvmLoggingTest.kt
- test-modules/logger-tests/src/jvmTest/kotlin/io/mockk/impl/log/JvmLoggingTest.kt
Small change, changing from kotlin test to Junit test to keep it consistent with other tests in same module.
Test is performing using Junit5 and assertions are using from Kotlin test.
> Update to Junit test

- modules/mockk/src/jvmTest/kotlin/io/mockk/it/CollectionsReturnOnRelaxedMockTest.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/it/ConcurrentStubInvocationTest.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/it/JavaClassParamTest.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/it/SafeCallSuspendingTest.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/jvm/ClassLoadingStrategyTest.kt
Update test from Junit 4 to Junit 5
> Update to Junit5 from Junit4

- modules/mockk/src/commonMain/kotlin/io/mockk/impl/recording/ChainedCallDetector.kt
Updated with right class name in logger
> Updated with right class name in logger

- modules/mockk/src/commonMain/kotlin/io/mockk/impl/verify/UnorderedCallVerifier.kt
Fixes https://github.com/mockk/mockk/issues/1016
> Don't call match an extra time during verification

- .github/workflows/gradle.yml
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/config/Deps.kt
- gradle.properties
- modules/mockk-agent/src/jvmMain/kotlin/io/mockk/proxy/jvm/JvmMockKAgentFactory.kt
* Update Kotlin to 1.8.0
* Update test matrix to use newest Kotlin/Java versions
~This is a draft while I try and figure out if any migrations are needed...~ Looks good, no changes required, or recommended by IntelliJ
> Update Kotlin to 1.8.0

- modules/mockk/src/commonTest/kotlin/io/mockk/impl/recording/CommonCallRecorderTest.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/impl/recording/states/RecordingStateTest.kt
- Edit CommonCallRecorderTest
- Add private modifier to properties
- Edit RecordingStateTest
- Delete test Ignore annotation
- Add private modifier to properties﻿
- Edit givenRecordingStateWhenLastCatchArgsHappensThenSignMatchersAndPermanentMockHappen test method
- Add newline at end of file
> Edit RecordingStateTest, CommonCallRecorderTest

- modules/mockk/src/commonTest/kotlin/io/mockk/it/CapturingGenericArgumentsTest.kt
- Delete test Ignore annotation
- Delete test comment
- Add private modifier to some methods
- Use single name import instead of wildcard import
> Edit CapturingGenericArgumentsTest

- test-modules/client-tests/src/jvmTest/kotlin/io/mockk/test/AnotherClientTest.kt
Update class declaration name to match with test class
> Update class declaration name to match with test class

- modules/mockk/src/jvmTest/kotlin/io/mockk/it/RurfTest.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/it/StackTraceLineNumberTest.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/it/StaticMockkTest.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/it/ThrowExceptionOnNonMockedClassTest.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/it/VerificationAcknowledgeTest.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/it/VoidReturnTest.kt
Small change, changing from kotlin test to Junit test to keep it consistent with other tests in same module.
Test is performing using Junit5 and assertions are using from Kotlin test.
> Update to Junit 5

- settings.gradle.kts
https://docs.gradle.com/enterprise/gradle-plugin/#using_build_scans
> Enable Gradle build scan publishing

- README.md
Corrected the "Top Level functions" section, to clarify the cancellation mechanism on the enclosing file.
Fixes #1061
> Amend "Top Level functions"

- modules/mockk-android/src/androidTest/java/io/mockk/ait/MockAbstractArgTest.kt
- modules/mockk-android/src/androidTest/java/io/mockk/ait/MockAbstractMethodTest.kt
- modules/mockk-android/src/androidTest/java/io/mockk/ait/MyAbstractClass.kt
- modules/mockk-core/src/jvmMain/kotlin/io/mockk/core/ValueClassSupport.kt
This resolves https://github.com/mockk/mockk/issues/1080.
> Fix error when mocking abstract method implementation

- README.md
Added a link to the Korean translation document in the README.md file.
I hope this pull request becomes a merge for Korean people.
> Add Korean guides and articles in README.md

- modules/mockk/src/commonMain/kotlin/io/mockk/impl/eval/RecordedBlockEvaluator.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/impl/instantiation/AnyValueGenerator.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/impl/log/SafeToString.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/impl/platform/CommonIdentityHashMapOf.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/impl/platform/CommonRef.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/impl/recording/ChainedCallDetector.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/impl/recording/states/SafeLoggingState.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/impl/stub/MockKStub.kt
Converting some functions to expression bodies while boyscouting the code
> chore: converting functions to expression bodies

- buildSrc/src/main/kotlin/buildsrc/config/Deps.kt
Changelog: https://github.com/raphw/byte-buddy/releases
> Update byte-buddy 1.14.6

- .github/workflows/gradle.yml
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/config/Deps.kt
This will need to be rebased on top of https://github.com/mockk/mockk/pull/1105
> Update Kotlin 1.9.10

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/android-library.gradle.kts
This plugin was never used in this project
> Remove AllOpen plugin from Android libraries

- modules/mockk-core/src/jvmMain/kotlin/io/mockk/core/ValueClassSupport.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/ValueClassTest.kt
Closes https://github.com/mockk/mockk/issues/544 https://github.com/mockk/mockk/issues/859
> Add support to nested value classes

- gradle.properties
> build(issue 1280): bump toolchain-jvm version to 17

- modules/mockk-agent-android/src/main/jni/mockkjvmtiagent/proxy-agent.cc
- modules/mockk-android/src/androidTest/java/io/mockk/MockConstructorTest.kt
> fix(1284): do not transform static constructor

- modules/mockk/src/commonMain/kotlin/io/mockk/impl/instantiation/CommonMockTypeChecker.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/impl/platform/CommonIdentityHashMapOf.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/impl/recording/ChainedCallDetector.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/impl/recording/states/VerifyingState.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/impl/verify/OrderedCallVerifier.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/impl/verify/SequenceCallVerifier.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/impl/verify/TimeoutVerifier.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/impl/verify/UnorderedCallVerifier.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/impl/verify/VerificationHelpers.kt
Converting some functions to expression bodies while boyscouting the code, also found a minor refactoring.
> chore: converting functions to expression bodies and minor function refactoring

- modules/mockk-dsl/src/commonMain/kotlin/io/mockk/API.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/impl/stub/MockKStubTest.kt
Add the `anyNullable` matcher.
> Add anyNullable

- README.md
> Fix compilation error in constructedWith docs

- modules/mockk/src/commonMain/kotlin/io/mockk/MockK.kt
related issue: https://github.com/mockk/mockk/issues/74
> Update the kdoc of verifyAll to describe its behavior correctly

- gradle/wrapper/gradle-wrapper.properties
> chore: bump gradle version to 8.14
