mockk/mockk

- README.md
Corrected the documentation for `verify` in the DSL.  (I do think excatly sounds better, from a purely cats-on-the-internet standpoint 😄
> Corrected excatly to exactly.

- README.md
- mockk-junit5/build.gradle
- mockk-junit5/src/main/kotlin/io/mockk/junit5/MockKJUnit5Extension.kt
- mockk-junit5/src/test/kotlin/io/mockk/junit5/MockKJUnit5ExtensionTest.kt
- settings.gradle
As mentioned in #23.
Take a good look at the `build.gradle` file please, I couldn't get Jacoco to run locally and there's probably a way to only use mockk-dsl but I couldn't get it to work.
> Mockk junit5

- mockk/src/main/kotlin/io/mockk/impl/InternalPlatform.kt
Now mockk is unusable with JDK7 'cause `Integer.toUnsignedString()` is private in it. This PR is an attempt to fix this incompatibility.
> fix JDK7 compatibility

- README.md
Changed the deprecated testCompile to the newer testImplementation. This will remove warnings on all recent Gradle versions. 
https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-and-compile-in-gradle/44493379#44493379
Also added the snippet for the Kotlin Gradle DSL.
https://github.com/gradle/kotlin-dsl
> Improved and updated Gradle dependency snippet

- README.md
- common/build.gradle
- common/src/main/kotlin/io/mockk/MockK.kt
- common/src/sample/kotlin/io/mockk/MockKSamples.kt
- common/src/test/kotlin/io/mockk/it/MatcherTest.kt
- dsl/common/src/main/kotlin/io/mockk/API.kt
Having the code `eq(x, true)` and `refEq(x, true)` might sometimes be too verbose and boilerplate.
I propose the matcher neq and nrefEq as a shortcut to both.
I believe the ideal would be to type `!eq(x)` and `!refEq(x)` but I couldn't find an alternative overloading operators, maybe in a further release.
> Added neq and nrefEq

- README.md
Adds Language specific syntax highlight to code blocks where language was missing in `README.md`.
This way the code snippets will be consistently highlighted instead of some being highlighted and other not.
> Adds Language specific syntax highlight to code blocks in documentation

- agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/transformation/FixParameterNamesVisitor.kt
Addresses #166 
This mimics Mockito's updates to this class: https://github.com/mockito/mockito/blame/release/2.x/src/main/java/org/mockito/internal/creation/bytebuddy/InlineBytecodeGenerator.java#L251
> Use OpenReader.ASM_API so we match bytebuddies ASM level

- mockk/jvm/src/test/kotlin/io/mockk/gh/Issue99Test.kt
The tested behaviour was incorrect in the sense that it tested if wasn't `123L` by chance. However, what this needs to test is that after unmocking the time doesn't equal the mocked time any longer.
> Improve Issue99Test

- README.md
I've added an extra article that I've written a while ago on Mockito and Kotlin.
I've also updated the example on capturing a list of arguments as there was an error in the same and because nothing was done to show that the list contained the two captured arguments.
Error:
``` kotlin
every {
obj.recordTelemetry(
speed = capture(list),
direction = Direction.SOUTH
)
} answers {
println(list.captured()) // probably copy paste error from the previous sample?
Outcome.RECORDED
}
```
> Add extra article and better example of capturing a list

- mockk/jvm/src/main/kotlin/io/mockk/impl/recording/JvmAutoHinter.kt
* The ClassCastException thrown in case of missing hints for erased
return types may have a null message when running in mixed mode.
* The code assumed the message can never be null. If it was null
nevertheless, a KotlinNullPointerException was thrown (instead of the
expected ClassCastException that should have been rethrown and would
have been translated into a useful message that a hint might be
necessary.)
This may solve or provide input for solving #240.
> JvmAutoHinter to cope with ClassCastExceptions with a message being null

- README.md
The version tag earlier was not quite accurate as it shows the latest version for the dependency being the one that is compatible with Koltin 1.2 and nothing about the one that is compatible with Kotlin1.3+
Just made it clear.
> Updated readme with version info tags

- mockk/common/src/main/kotlin/io/mockk/impl/verify/OrderedCallVerifier.kt
Grammatical error. 
"Then" should be used when comparing two things (actual calls vs demanded calls)
> Change then to than

- mockk/common/src/test/kotlin/io/mockk/it/VerificationErrorsTest.kt
Fix failing Unit Test
Change "then" to "than".
Missed the changes in unit test when changing the implementation 
Reference: #314
> Fix unit test PR #314

- gradle/upload-archives.gradle
http://www.github.com is redirected to https://github.com
> Fix pom scm.url

- README.md
- dsl/common/src/main/kotlin/io/mockk/API.kt
- mockk/common/src/test/kotlin/io/mockk/gh/Issue346Test.kt
Convenience syntax as an alternative to any of the following:
- `every { mock["privateMethod"]() } answers(ConstantAnswer(Unit))`
- `every { mock["privateMethod"]() as Unit} just runs`.
Resolves issue #346.
> Provide invokeReturnsUnit for private functions returning Unit

- dsl/common/src/main/kotlin/io/mockk/API.kt
- dsl/common/src/main/kotlin/io/mockk/Matchers.kt
- mockk/common/src/test/kotlin/io/mockk/gh/Issue323Test.kt
As reported on issue #323, the function `withNullableArg` is not working properly when receiving a null value. 
The problem comes from `TypedMatcher` interface and its `checkType` method. When `InvocationMatcher` executes its `match` method and the matcher is a `TypedMatcher`, the mentioned `checkType` method is executed and makes the invocation matcher to return false for any null argument. 
````
fun checkType(arg: Any?): Boolean {
if (argumentType.simpleName === null) {
return true
}
return argumentType.isInstance(arg)
}
````
`KClass.isInstance` method is going to always return false if the arg's value is null. Therefore we have a problem with `TypedMatcher` and null values.
The proposed solution consists of creating a new `FunctionMatcher` for nullable arguments …
> Fix 'withNullableArg' function to make it work properly with null values (#323)

- agent/android/build.gradle
@oleksiyp This should be enough to get me past this issue as it results in the creation of binaries that target the same architecture that I do: https://github.com/mockk/mockk/issues/297
I'm totally unaware of your policy regarding accepting community contributions and how you like to perform releases, so I'm willing to make updates as necessary.
> add x86_64 and arm64-v8a mockkjvmtiagent so

- gradle/jacoco.gradle
Jacoco does not work properly out of the box with JDK11+, so gradle builds results in this error being logged:
```
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
at java.base/java.lang.Class.getField(Class.java:1976)
at org.jacoco.agent.rt.internal_c13123e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
... 9 more
```
And builds hanging forever.
As discussed [here](https://github.com/vaskoz/core-java9-impatient/issues/11) this is due to an issue in Jacoco that was fixed in v0.8.2.
By default Jacoco uses an older version, so to make the builds pass on JDK11+ explicitly setting the version to 0.8.2 is required.
> Updated Jacoco version to work with JDK11+

- README.md
This PR fixes typos of the README file.
> Fix typo from MockKAnntations to MockKAnnotations

- mockk/common/src/main/kotlin/io/mockk/impl/instantiation/AnyValueGenerator.kt
- mockk/common/src/test/kotlin/io/mockk/impl/instantiation/AnyValueGeneratorTest.kt
- mockk/jvm/src/main/kotlin/io/mockk/impl/instantiation/JvmAnyValueGenerator.kt
- mockk/jvm/src/test/kotlin/io/mockk/gh/Issue386Test.kt
This fixes #386 by providing anyValue implementations for some common collections, like list, map, set and their most common implementations.
> Added collections to the AnyValueGenerator

- mockk/jvm/src/main/kotlin/io/mockk/impl/JvmMultiNotifier.kt
When running the Android Instrumented test (`verify(timeout = 1000) {}`) with API <= 23, exception occurs with stack trace:
```
E/TestRunner: java.lang.NoSuchMethodError: No interface method getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Ljava/util/Map; or its super classes (declaration of 'java.util.Map' appears in /system/framework/core-libart.jar)
at io.mockk.impl.JvmMultiNotifier.changeCounters(JvmMultiNotifier.kt:63)
at io.mockk.impl.JvmMultiNotifier.openSession(JvmMultiNotifier.kt:18)
at io.mockk.impl.stub.StubRepository.openRecordCallAwaitSession(StubRepository.kt:37)
at io.mockk.impl.verify.TimeoutVerifier.verify(TimeoutVerifier.kt:19)
at io.mockk.impl.recording.states.VerifyingState$recordingDone$outcome$1.invoke(VerifyingState.kt:31)
at …
```
> Use `getOrElse` instead of `getOrDefault`

- dsl/common/src/main/kotlin/io/mockk/Matchers.kt
- mockk/common/src/test/kotlin/io/mockk/gh/Issue389Test.kt
This fixes #389 by making sure that if a FunctionMatcher's `matchingFunc` throws an `AssertionError`, it is just considered non-matching rather than propagating the Error across all the application.
> Fixed issue 389 by catching AssertionErrors in the FunctionMatcher

- README.md
> Fix typo in README: Teting -> Testing

- mockk/common/src/main/kotlin/io/mockk/MockK.kt
This PR adds missing documentation for the following `verify()` method parameters: `timeout`, `verifyBlock`.
The most important is the `timeout`'s doc as it's confusing not to know what time unit is used for it. :smile:
> Add missing documentation for the verify method parameters

- README.md
Assigning single element to varargs in named form has been deprecated and is now forbidden.
> Fix documentation referring to `moreInterfaces`

- mockk/common/src/main/kotlin/io/mockk/impl/verify/OrderedCallVerifier.kt
- mockk/common/src/test/kotlin/io/mockk/it/VerificationErrorsTest.kt
Very, VERY trivial grammar correction to assertion failure. I apologise in advance for my pedantry!
Context: [Fewer vs. Less](https://www.grammarly.com/blog/fewer-vs-less/)
> "Fewer" not "less"

- agent/android/src/main/kotlin/io/mockk/proxy/android/AndroidMockKAgentFactory.kt
This PR aims to fix https://github.com/mockk/mockk/issues/351 by taking advantage of `setHiddenApiExemptions` as mentioned in [this stack overflow answer](https://stackoverflow.com/a/55970138).
We're currently using this logic for Android tests as part of our `AndroidJUnitRunner`, but I think it makes sense to bring this into `mockk` as other people seem to be facing the same issue.
I've published these changes as a snapshot to maven local and it seems to do the trick - tested on P and R emulators and a physical Q device. 
@oleksiyp, let me know if you think this belongs somewhere different or if there are any cases you think it'd be good to test.
> Fix issue 351 by setting hiddenApiExemptions

- mockk/jvm/src/main/kotlin/io/mockk/junit5/MockKExtension.kt
- mockk/jvm/src/test/kotlin/io/mockk/gh/Issue445Test.kt
This intent of this PR is to fix the #445 issue using JUnit methods for finding annotations
> [#445] Fix MockKExtension support on JUnit 5 for constructor injection

- agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/ObjenesisInstantiator.kt
In a Robolectric testing environment, a new ClassLoader is created per
Android SDK level. Because of this, using MockK objects across SDK
levels is very likely to cause ClassCastException. Disable the Objenesis
cache on the JVM which makes MockK work more seamlessly in environments
with multiple ClassLoaders.
Fixes https://github.com/robolectric/robolectric/issues/5848
> Disable Objenesis cache on the JVM

- README.md
- mockk/jvm/src/main/kotlin/io/mockk/MockK.kt
- mockk/jvm/src/test/kotlin/io/mockk/it/StaticMockJVMTest.kt
Adds a `jvm`-only `mockkStatic` overload function that will allow passing a function reference to pick up the `declaringClass`.
This allows to write more robust tests as hardocded class references like:
```kotlin
// declared in File.kt ("pkg" package)
fun Obj.extensionFunc() = value + 5
mockkStatic("pkg.FileKt")
```
Can now be just:
```kotlin
// declared in File.kt ("pkg" package)
fun Obj.extensionFunc() = value + 5
mockkStatic(Obj::extensionFunc)
```
> Added `mockkStatic` hard reference support

- mockk/common/src/main/kotlin/io/mockk/impl/instantiation/AnyValueGenerator.kt
- mockk/common/src/test/kotlin/io/mockk/gh/Issue510Test.kt
- mockk/common/src/test/kotlin/io/mockk/impl/instantiation/AnyValueGeneratorTest.kt
- mockk/jvm/src/main/kotlin/io/mockk/impl/JvmMockKGateway.kt
- mockk/jvm/src/main/kotlin/io/mockk/impl/instantiation/JvmAnyValueGenerator.kt
- mockk/jvm/src/main/kotlin/io/mockk/impl/instantiation/JvmInstantiator.kt
- mockk/jvm/src/test/kotlin/io/mockk/jvm/JvmAnyValueGeneratorTest.kt
This fixes #510.
A change introduced in 1.10.2 added default answers for collections by using the helper `listOf()`, `mapOf()`...functions.
However, these all return the same instance of the corresponding collection, so when the `AnyValueGenerator` was used in creating matchers for recording calls the signature determination was broken: blocks stubbed as
```
every { doSomething(any(), any()) } just runs
```
Where both parameters are `List`s were being mistakenly matched as `doSomething(any(), eq([])`.
By making sure that the `AnyValueGenerator´ always returns a new instance of collections, the signatures now take into account different values of the same type and result in proper matchers.
> Changed the answers for collections to return a new instance every time

- mockk/common/src/main/kotlin/io/mockk/impl/verify/LCSMatchingAlgo.kt
- mockk/common/src/main/kotlin/io/mockk/impl/verify/UnorderedCallVerifier.kt
- mockk/common/src/test/kotlin/io/mockk/gh/Issue352Test.kt
- mockk/common/src/test/kotlin/io/mockk/gh/Issue353Test.kt
- mockk/jvm/src/main/kotlin/io/mockk/impl/InternalPlatform.kt
- mockk/jvm/src/test/kotlin/io/mockk/gh/Issue386Test.kt
This checks if a `verify` block contains the same function more than once and slots are being used to capture its arguments.
If this is the case, the `captured` property of the slot will contain only the argument of the last call, with the tests not behaving as expected.
An exception is now thrown in this case, to suggest using a mutableList to capture arguments.
This should fix #352 by clarifying to users the right way to capture multiple invocations of the same function.
> Added a check to prevent slots from being used when verifying multiple calls

- build.gradle
- matrix/jvm.gradle
- mockk/common/src/main/kotlin/io/mockk/impl/eval/RecordedBlockEvaluator.kt
This upgrades the Kotlin version to 1.4.
All tests run fine except for Issue158Test: functions returning Nothing don't throw a NPE anymore in Kotlin 1.4, but they throw a KotlinNothingValueException.
Unfortunately, this is an internal exception, so it cannot be caught or referenced directly.
The hacky solution is to catch `Exception` in the `enhanceWithRethrow` function: it will rethrow any exceptions that were not thrown because the last call was returning Nothing, so it shouldn't break any existing behaviors.
> Upgraded kotlin to 1.4 and fixed the Nothing-related NPE rethrow

- gradle/jvm-module.gradle
Set source and target compatibility to 1.8, to ensure jars produced with newer runtimes are still compatible with at least Java 8.
Fixes #539.
> Fix class file compatibility issue with mockk-agent-jvm

- agent/jvm/src/main/java/io/mockk/proxy/jvm/advice/jvm/JvmMockKConstructorProxyAdvice.java
- agent/jvm/src/main/java/io/mockk/proxy/jvm/advice/jvm/JvmMockKHashMapStaticProxyAdvice.java
- agent/jvm/src/main/java/io/mockk/proxy/jvm/advice/jvm/JvmMockKProxyAdvice.java
- agent/jvm/src/main/java/io/mockk/proxy/jvm/advice/jvm/JvmMockKProxyInterceptor.java
- agent/jvm/src/main/java/io/mockk/proxy/jvm/advice/jvm/JvmMockKStaticProxyAdvice.java
- agent/jvm/src/main/java/io/mockk/proxy/jvm/advice/jvm/MockHandlerMap.kt
- agent/jvm/src/main/java/io/mockk/proxy/jvm/dispatcher/JvmMockKDispatcher.java
- agent/jvm/src/main/java/io/mockk/proxy/jvm/dispatcher/JvmMockKWeakMap.java
- agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/JvmMockKAgentFactory.kt
- agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/advice/BaseAdvice.kt
- agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/transformation/InliningClassTransformer.kt
- agent/jvm/src/main/kotlin/io/mockk/proxy/jvm/transformation/SubclassInstrumentation.kt
- mockk/jvm/src/test/kotlin/io/mockk/jvm/HashMapMockTest.kt
Fix infinite loop when concurrent hashmap is spied. Discovered that abstract map mocking is not working. Should fix #273
> Fix #273 infinite loop when concurrentHashMap is spied

- README.md
- dsl/common/src/main/kotlin/io/mockk/MockKSettings.kt
- dsl/js/src/main/kotlin/io/mockk/MockKSettings.kt
- dsl/jvm/src/main/kotlin/io/mockk/MockKSettings.kt
- mockk/common/src/main/kotlin/io/mockk/impl/verify/VerificationHelpers.kt
This adds a config setting to drive the alignment of the stacktraces printed when a verification fails.
It should fix #89 by allowing users to change the stacktraces alignment if they'd like to have it more consistent with the usual JVM behavior.
> Added a configuration setting to drive stack traces alignment

- agent/android/src/main/kotlin/io/mockk/proxy/android/AndroidMockKAgentFactory.kt
Proposed fix for https://github.com/mockk/mockk/issues/519.
The workaround introduced in https://github.com/mockk/mockk/pull/442 for allowing [hidden APIs](https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces) to be accessed via reflection no longer works from API 30. This PR ensures that the workaround is not applied in this case
This means that https://github.com/mockk/mockk/issues/351 will occur for API 30 and above, but this would be a smaller issue.
In the long term, to fix https://github.com/mockk/mockk/issues/351 for later APIs, it might be worth trying to integrate https://github.com/ChickenHook/RestrictionBypass which offers another solution.
> Fix issue 519 by not applying setHiddenApiExemptions workaround for API 30+

- mockk/common/src/main/kotlin/io/mockk/impl/recording/states/StubbingState.kt
- mockk/jvm/src/test/kotlin/io/mockk/gh/Issue538Test.kt
Proposed fix for #538.
Exception message that is being thrown when a non mocked class is in every block it's not clear.
`Missing calls inside every { ... } block.`
`Cannot use every { ... } block with a non mocked class`
> Fix #538: Change exception message when using not mocked class in every block

- agent/android/src/main/kotlin/io/mockk/proxy/android/AndroidMockKAgentFactory.kt
- agent/android/src/main/kotlin/io/mockk/proxy/android/advice/Advice.kt
- client-tests/jvm/src/test/kotlin/io/mockk/test/BasicClientTest.kt
- mockk/android/build.gradle
- mockk/android/src/androidTest/java/io/mockk/gh/Issue563Test.kt
- mockk/android/src/debug/AndroidManifest.xml
- mockk/android/src/debug/java/io/mockk/debug/TestActivity.kt
- mockk/common/src/test/kotlin/io/mockk/gh/Issue352Test.kt
- mockk/common/src/test/kotlin/io/mockk/gh/Issue510Test.kt
- mockk/jvm/src/test/kotlin/io/mockk/gh/Issue323Test.kt
- mockk/jvm/src/test/kotlin/io/mockk/gh/Issue99Test.kt
Following on from my comments in https://github.com/mockk/mockk/issues/563, I have applied the workaround from dexmaker for `MethodDescriptor` for Android R. This fixes the issue of mocking Android SDK objects in classes that also use real ones.
For this to work, I had to make a couple of additional changes:
1. To make the android tests run locally, I had to remove the back tick method names from tests. I'm not sure why the unit tests in `mockk-common` are being compiled as part of the androidTests in `mockk-android`, but maybe this is just a local issue. I'm happy to drop this change if the tests work elsewhere.
2. The `isOverridden` extension function in `Advice` began to throw with a null `superclass` after I applied the workaround. I worked around this by making the receiver nullable, …
> Fix issue 563 by allowing hidden api reflection from MethodDescriptor

- mockk/jvm/src/main/kotlin/io/mockk/junit5/MockKExtension.kt
- mockk/jvm/src/test/kotlin/io/mockk/junit5/MockKExtensionTest.kt
Closes #142 
As explained in https://github.com/mockk/mockk/issues/142#issuecomment-781674022 I think that the associated test needs to be adapted because the tests in `MockKExtensionTest` don't seem to get run at all.
> Unmock all after each test with JUnit5 extension

- .github/workflows/gradle.yml
- gradle/jacoco.gradle
So tests will be run on multiple Java versions. I also added a cache.
Building releases from tags and uploading them should be possible, too. 
I'm a bit concerned about the failing regression test for `Issue3test89Test` - are you perchance aware of that?
> Add CI test matrix

- README.md
- mockk/jvm/src/main/kotlin/io/mockk/MockK.kt
- mockk/jvm/src/test/kotlin/io/mockk/it/StaticMockJVMTest.kt
We have found another use case for `mockkStatic`. Basically it's syntax sugar for when you try to mock an extension property like this:
```kotlin
val Int.square get()= this * this
```
> Added `mockkStatic` support for `val Any.xxx get()`

- dsl/jvm/src/main/kotlin/io/mockk/InternalPlatformDsl.kt
as per issue #304 a hint to supply function arguments when trying to mock a private function it's added to the exception message.
> FIX 304: better error messages

- mockk/common/src/main/kotlin/io/mockk/impl/verify/LCSMatchingAlgo.kt
- mockk/common/src/test/kotlin/io/mockk/gh/Issue614Test.kt
Added safe calls in the `LCSMatchingAlgo` to avoid `ArrayIndexOutOfBoundException` as in #614 .
The output in this scenario is now:
```
java.lang.AssertionError: Verification failed: fewer calls happened than demanded by order verification sequence. 
Matchers: 
Something(#732).doSomething())
Calls:
```
> fix[614]: ArrayIndexOutOfBoundException in verifyOrder when no call was recorded

- mockk/jvm/src/main/kotlin/io/mockk/ValueClassSupport.kt
- mockk/jvm/src/main/kotlin/io/mockk/impl/instantiation/JvmMockFactoryHelper.kt
- mockk/jvm/src/test/kotlin/io/mockk/it/RelaxedSuspendingMockingTest.kt
The previous #641 implemetnation was buggy, a fix here.
> fix reading return type for suspending function returning generic type

- agent/android/src/main/kotlin/io/mockk/ValueClassSupport.kt
- agent/jvm/src/main/kotlin/io/mockk/ValueClassSupport.kt
- dsl/common/src/main/kotlin/io/mockk/API.kt
- mockk/common/src/main/kotlin/io/mockk/impl/instantiation/AnyValueGenerator.kt
- mockk/common/src/main/kotlin/io/mockk/impl/recording/CommonCallRecorder.kt
- mockk/common/src/main/kotlin/io/mockk/impl/recording/WasNotCalled.kt
- mockk/common/src/main/kotlin/io/mockk/impl/recording/states/RecordingState.kt
- mockk/common/src/main/kotlin/io/mockk/impl/stub/MockKStub.kt
- mockk/common/src/main/kotlin/io/mockk/impl/stub/StubGatewayAccess.kt
- mockk/common/src/test/kotlin/io/mockk/impl/instantiation/AnyValueGeneratorTest.kt
- mockk/common/src/test/kotlin/io/mockk/it/RelaxedMockingTest.kt
- mockk/js/src/main/kotlin/io/mockk/impl/JsMockKGateway.kt
- mockk/js/src/main/kotlin/io/mockk/impl/instantiation/JsMockFactory.kt
- mockk/jvm/src/main/kotlin/io/mockk/ValueClassSupport.kt
- mockk/jvm/src/main/kotlin/io/mockk/impl/JvmMockKGateway.kt
- mockk/jvm/src/main/kotlin/io/mockk/impl/instantiation/JvmAnyValueGenerator.kt
- mockk/jvm/src/main/kotlin/io/mockk/impl/instantiation/JvmMockFactory.kt
- mockk/jvm/src/main/kotlin/io/mockk/impl/instantiation/JvmMockFactoryHelper.kt
- mockk/jvm/src/test/kotlin/io/mockk/it/NullableValueGeneratorTest.kt
- mockk/jvm/src/test/kotlin/io/mockk/jvm/JvmAnyValueGeneratorTest.kt
> Custom any value generator

- README.md
When I was reading mockk readme document, I found some `obj` are used, which seems incorrect name. So I renamed them to `car`.
> rename some `obj` to `car` in readme sample code

- mockk/jvm/src/main/kotlin/io/mockk/impl/annotations/MockInjector.kt
- mockk/jvm/src/test/kotlin/io/mockk/impl/annotations/MockInjectorTest.kt
Currently, when using `@InjectMockKs` annotation with constructor injection, it is required to provide mocked values for all constructor arguments, even if they are optional and have default values (See example below). 
With this PR `@InjectMockks` will still look for mockks for all parameters, including optional, but if nothing is found, default value will be used.
```
class Example (param1: Param1, param2: Param2 = Param2()) {...}
...
@Mockk
lateinit var param1: Param1
@InjectMockks //Will not work since no mockk for param2 is provided
lateinit var example: Example
```
> Add optional constructor arguments support for @InjectMockKs

- build.gradle
- gradle/android-module.gradle
- gradle/jvm-module.gradle
- matrix/android.gradle
- matrix/jvm.gradle
> JFrog announced the decommission of JCenter. This has the potential to impact
> many Gradle builds. Gradle emits a deprecation warning when jcenter() is used
> in the repository configuration. Consider using mavenCentral(), google() or a
> private maven repository instead.
https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#jcenter_deprecation
> remove deprecated jcenter repository

- README.md
Corrects some minor grammatical errors and unnatural wordings, which made the doc harder for me to read (as a native English speaker).
> Improve English grammar in README doc

- agent/jvm/src/main/java/io/mockk/proxy/jvm/ClassLoadingStrategyChooser.java
- mockk/jvm/src/test/kotlin/io/mockk/jvm/Issue280.kt
Apparently javax.sql.DataSource is loaded via a different classloader, which leads to a missing instrumenter. Found similar fix has been applied to jmock. Fixes #280
> Fix mocking of  javax.sql.DataSource

- mockk/common/src/main/kotlin/io/mockk/impl/recording/states/RecordingState.kt
- mockk/jvm/src/test/kotlin/io/mockk/it/CollectionChainStubbingTest.kt
Issue: https://github.com/mockk/mockk/issues/565
Changes that affected expected behavior: https://github.com/mockk/mockk/pull/387, https://github.com/mockk/mockk/pull/536
Any feedback is appreciated. I'm completely new to the internals of MockK, so please excuse any shortcomings of my solutions.
**I recommend checking commits separately**, because there are alternative solutions. I'll clean those up in case a solution is chosen.
Tests pass for both solutions.
This is an attempt at fixing stubbing by chained calls on collection, such as:
```kotlin
val mock = mockk<SomeClass>()
every { mock.map.get("foo") } returns 0
```
Expected behavior broke when `(Jvm)AnyValueGenerator` started returning concrete instances for collection types. Before those branches existed, the generator would fall …
> Fix stubbing by chained calls on collections (#565)

- README.md
The mockk-agent-jvm dependency is now a 'hard requirement' for projects in Android Studio ArticFox (and later): https://stackoverflow.com/questions/68872301/android-studio-arctic-fox-unable-to-run-junit-configuration-with-mockk/68990942#68990942
Closes #605
> Update README.md for mockk-agent-jvm in Android Studio ArticFox++

- README.md
- mockk/jvm/src/main/kotlin/io/mockk/junit5/MockKExtension.kt
- mockk/jvm/src/test/kotlin/io/mockk/junit5/MockKExtensionAfterAllTestTest.kt
- mockk/jvm/src/test/kotlin/io/mockk/junit5/MockKExtensionTest.kt
This change is motivated by the comment I've dropped at https://github.com/mockk/mockk/issues/142#issuecomment-964500401.
`MockKExtension` is calling `unmockkAll` by default at the end of *each* test, which interferes with the `@TestInstance(TestInstance.Lifecycle.PER_CLASS)`  configuration.
We discovered this issue after enabling `junit.extensions.autodetection.enabled=true` (by other rules, not this one) and all tests with cached mocks (per instance) started to fail because of the reset.
This PR moves the `unmockkAll`  behavior to the `afterAll` callback, and also introduces a new `@KeepMocks` (and a `mockk.junit.extension.keepmocks` property) to allow disabling just this feature while keeping the others of `MockKExtension`.
> Moves `MockKExtension`'s `unmockkAll` behavior to the `afterAll` callback

- agent/jvm/src/test/java/io/mockk/proxy/JvmMockKProxyMakerTest.java
`throws Exception` is not required in these test methods and flagged as warnings by IDE.
> Removed unnecessary throws exception from test class

- plugins/dependencies/src/main/kotlin/io/mockk/dependencies/Deps.kt
JUnit upgrade to latest version `5.8.2`
https://junit.org/junit5/docs/current/release-notes/index.html#release-notes
> JUnit 5 upgrade to latest version

- dsl/common/src/main/kotlin/io/mockk/Matchers.kt
Based on the issue documented [here](https://github.com/mockk/mockk/issues/707), there is no logging when a matcher using `withArg` fails due to a nested assertion exception. After some discussion, it was determined that the best solution would be to remove the try/catch from the matcher so that the error will bubble up and be logged when it fails the matching
> Added logging when matcher fails with an assertion error

- agent/jvm/src/main/java/io/mockk/proxy/jvm/ClassLoadingStrategyChooser.java
This fixes an issue using MockK on classes defined in a Robolectric
class loader.
Fixes #754
Partially fixes https://github.com/robolectric/robolectric/issues/5871
> Avoid Lookup strategy when constructing javax classes

- README.md
Quarkus also support `mockk` as mock provider in the bean container. This adds the link to the library. 
Thanks for your work on this project!
> Add quarkus support section

- dsl/jvm/src/main/kotlin/io/mockk/InternalPlatformDsl.kt
- mockk/jvm/src/test/kotlin/io/mockk/it/PrivateParentMethodTest.kt
- Add support for mocking non-accessible parent methods using Mockk
- The class being mocked is always searched first for the specified
method, then all superclasses are checked in no specific order. If
multiple superclasses have matching signatures for the method then
there is no guarantee which will be chosen.
- Fixes #425
> Support mocking non-accessible parent methods

- README.md
- mockk/jvm/build.gradle.kts
- mockk/jvm/src/main/kotlin/io/mockk/junit4/MockKRule.kt
- mockk/jvm/src/test/kotlin/io/mockk/junit4/MockKRuleTest.kt
I find myself using something like this in most of my personal projects, it saves a lot (okay not that much) boilerplate of calling `MockKAnnotations.init(this)` and `unmockkAll()` in every JUnit 4 test case.
I essentially copypasted the test case from the equivalent for `MockKExtension`, let me know if that's not okay.
> Added a JUnit 4 rule

- README.md
- dsl/common/src/main/kotlin/io/mockk/API.kt
- dsl/common/src/main/kotlin/io/mockk/GatewayAPI.kt
- mockk/common/src/main/kotlin/io/mockk/MockK.kt
- mockk/common/src/main/kotlin/io/mockk/impl/recording/CommonVerificationAcknowledger.kt
- mockk/common/src/main/kotlin/io/mockk/impl/stub/ConstructorStub.kt
- mockk/common/src/main/kotlin/io/mockk/impl/stub/MockKStub.kt
- mockk/common/src/main/kotlin/io/mockk/impl/stub/Stub.kt
- mockk/jvm/api/mockk-jvm.api
- mockk/jvm/src/main/kotlin/io/mockk/junit5/MockKExtension.kt
- mockk/jvm/src/test/kotlin/io/mockk/it/VerificationAcknowledgeTest.kt
[Automatic verification confirmation](https://github.com/mockk/mockk#automatic-verification-confirmation) introduces a new mechanism that ensure that all declared stubs are verified. This is cool but doesn't exactly match which is requested in #558 and exposed in [mockito doc](http://site.mockito.org/javadoc/current/index.html?org/mockito/exceptions/misusing/UnnecessaryStubbingException.html)
This PR add a new `checkUnnecessaryStub()` method, and its companion JUnit annotion `@CheckUnnecessaryStub`.
The main usecase of this feature is to avoid the `verify` steps when all stubs are done with precision and every stubs are used only once.
> Better detection of unnecessary stubbing

- .github/workflows/gradle.yml
- README.md
- agent/jvm/api/mockk-agent-jvm.api
- build.gradle
- dsl/common/src/main/kotlin/io/mockk/MockKSettings.kt
- gradle.properties
- gradle/upload.gradle
- mockk/common/src/main/kotlin/io/mockk/MockK.kt
- mockk/common/src/main/kotlin/io/mockk/impl/recording/PermanentMocker.kt
- mockk/common/src/main/kotlin/io/mockk/impl/recording/states/StubbingAwaitingAnswerState.kt
- mockk/common/src/main/kotlin/io/mockk/impl/recording/states/VerifyingState.kt
- mockk/jvm/src/main/kotlin/io/mockk/impl/InternalPlatform.kt
- plugins/dependencies/src/main/kotlin/io/mockk/dependencies/Deps.kt
This PR updates the version of Kotlin to the latest version, 1.7.10.
~I also set the API and language levels to 1.7. I have NO idea if this is the best choice! On one hand, I think it's best to 'go big or go home' - this kind of change only needs to be done once, and now mockk is at a high language level that will be available for years. On the other hand, perhaps maintaining and providing as wide compatibility is best.~ discussed below, will bump to 1.5
I'm making this change to help work related to supporting value classes - see #152 and #849 
* bumped Kotlin to 1.7.10
* bumped Kotlin language & API levels to 1.5 
* regenerated binary-compatibility API specs
* updated the GitHub action matrix to remove 1.4 and add 1.7
* minor Kotlin migrations
* `toUpperCase()` -> `uppercase()`, …
> bump kotlin 1.7.10, and language level to 1.5

- .github/workflows/gradle.yml
- gradle.properties
This PR contains some proposals for improving the 'all tests' GitHub action. I hope to make them faster.
I'm making a PR before an issue to test/demo that it works as intended :)
* Only test LTS JDK versions (11, 17), plus the latest version (18 at the moment - this can change more frequently). I'm making an assumption here that there's not going to be major differences between the non-LTS versions, and even if there are, as far as I know they're not well supported. 
Reducing the number of versions improves the actions speed, as I think there's a limit on how many jobs can run in parallel.
* Add 'concurrency'. I've noticed when I've pushed a few changes in rapid succession, each change will be tested. This isn't necessary - the tests should be cancelled and restarted if there's a newer …
> Update 'all tests' GitHub action, enable Gradle Build Cache

- mockk/common/src/test/kotlin/io/mockk/it/SealedClassTest.kt
- mockk/common/src/test/kotlin/io/mockk/it/SealedInterfaceTest.kt
Providing tests for #832. They work locally for me, but I'm not running JDK17 - I'm committing so the automated tests can check all versions. Perhaps #850 fixed it?
Tests copied from here: https://github.com/mockk/mockk/issues/832#issuecomment-1175857282
> #832 Add tests for sealed classes

- dsl/common/src/main/kotlin/io/mockk/API.kt
- mockk/common/src/test/kotlin/io/mockk/it/ConstructorMockTest.kt
Hi all! 
This PR is to fix the Issue #838 
I changed `internalMockkConstructor` to work like `internalMockkObject` and `internalMockkStatic` by changing it to use `cancelPut`
I added a new test but I had to remove `test2`.
I'm unsure what exactly they test, but with my change the mocked instance in `ExampleObject` `private val exampleClass` is reset once mockkConstructor is called again in test2. And since it's in an object which is not reset between test1 and test2, test2 fails because it is not re-instantiated with the mocked class.
> Fix unmockkAll to work if constructor was mocked multiple times

- agent/android/src/main/kotlin/io/mockk/ValueClassSupport.kt
- agent/jvm/src/main/kotlin/io/mockk/ValueClassSupport.kt
- dsl/jvm/src/main/kotlin/io/mockk/ValueClassSupportDsl.kt
- mockk/common/src/test/kotlin/io/mockk/it/ValueClassTest.kt
To get value class property we need to find the one property with a backing field because value classes can have any number of properties without a backing field as well.
> fix: fix value class field determination

- buildSrc/src/main/kotlin/buildsrc/convention/mockk-publishing.gradle.kts
Quick fix to allow for publishing to Maven Local without having the signing properties set up.
This was useful here: https://github.com/mockk/mockk/issues/883#issuecomment-1223585788
> only sign if the signing properties are present

- buildSrc/src/main/kotlin/buildsrc/convention/android-library.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/mockk-publishing.gradle.kts
Fixes: https://github.com/mockk/mockk/issues/883
The official Android documentation about publications is [here](https://developer.android.com/studio/publish-library/upload-library#create-pub).
I confirmed that `mockk-android` is published with the following command.
```
$ ./gradlew publishToMavenLocal
$ tree ~/.m2/repository/io/mockk/
~/.m2/repository/io/mockk
├── mockk
│   ├── 1.12.7-SNAPSHOT
│   │   ├── maven-metadata-local.xml
│   │   ├── mockk-1.12.7-SNAPSHOT-javadoc.jar
│   │   ├── mockk-1.12.7-SNAPSHOT-kotlin-tooling-metadata.json
│   │   ├── mockk-1.12.7-SNAPSHOT-sources.jar
│   │   ├── mockk-1.12.7-SNAPSHOT.jar
│   │   ├── mockk-1.12.7-SNAPSHOT.module
│   │   └── mockk-1.12.7-SNAPSHOT.pom
│   └── maven-metadata-local.xml
├── mockk-agent
│   ├── 1.12.7-SNAPSHOT
│   │   ├── …
```
> Fix an issue that Android libraries was not published

- modules/mockk-agent-android/build.gradle.kts
Fixes #894
My take on #895 - credit to @kubode for identifying the problem and showing how to check it.
What do you think @kubode?
It also includes using the Gradle task output - this helps with Gradle task optimisation. Wrapping the task in a lambda prevents the NPE.
The issue in this comment is also resolved https://github.com/mockk/mockk/pull/895#issuecomment-1225519166
> Fix Android Instrumentation dispatcher.jar inclusion

- .github/workflows/gradle.yml
- buildSrc/src/main/kotlin/buildsrc/convention/android-application.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/android-library.gradle.kts
Might resolve #893.
Changing minSdk was done in PR #863 , which was a modified PR based on #829. I don't know if the minSdk is required to be 26 - it doesn't seem like 23 has any problems.
> try reverting Android minSdk to 21

- .github/workflows/gradle.yml
- build.gradle.kts
Use the official Gradle GitHub Action https://github.com/marketplace/actions/gradle-build-action
Two reasons: 
1. I've noticed that the GitHub actions aren't always cached, and thus they take longer than necessary
2. Less configuration is needed
> use the official Gradle GHA

- .github/workflows/gradle.yml
Just a quick test to make sure there are no issues ahead of the release. Either this can be merged now, or later once 1.7.20 is released properly - I'm not sure which is best.
> add 1.7.20-RC to test matrix

- modules/mockk-core/src/jvmMain/kotlin/io/mockk/core/ValueClassSupport.kt
- test-modules/client-tests/build.gradle.kts
- test-modules/client-tests/src/jvmTest/java/io/mockk/core/JavaEnum.java
- test-modules/client-tests/src/jvmTest/kotlin/io/mockk/core/ValueClassSupportTest.kt
might fix #868 ~caused by #913?~ not caused by #913, it seems `KotlinReflectionInternalError` was never caught...
~This is a draft because I want to make a test for this to make sure it doesn't happen again. See https://youtrack.jetbrains.com/issue/KT-41373 for reproductions.~ Test added
> value class check - catch KotlinReflectionInternalError

- README.md
* Removed `-jvm` dependency from Gradle dependencies - Gradle will automatically determine the correct platform
* I removed the 'common' dependency because `mockk-common` doesn't exist any more
* Changed `{version}` to `{mockkVersion}`, because in Gradle `$version` will refer to the Project version.
> update dependencies in readme to reflect new multiplatform structure

- modules/mockk-agent/src/jvmMain/kotlin/io/mockk/proxy/jvm/ProxyMaker.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/SealedClassTest.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/SealedInterfaceTest.kt
Attempt to fix https://github.com/mockk/mockk/issues/832 by supporting sealed classes based on previous work done by @aSemy.
> Properly handle sealed classes with Kotlin 1.7 and JDK 17

- .github/workflows/gradle.yml
- README.md
- buildSrc/src/main/kotlin/buildsrc/config/Deps.kt
- modules/mockk-dsl/api/mockk-dsl.api
- modules/mockk-dsl/src/commonMain/kotlin/io/mockk/API.kt
- modules/mockk/api/mockk.api
- modules/mockk/build.gradle.kts
- modules/mockk/src/commonMain/kotlin/io/mockk/MockK.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/CoJustAwaitTest.kt
And adding kotlinCoroutinesTest dependency for testing purposes.
Examples:
```kotlin
coJustAwait { mock.coOp() }
coEvery { mock.coOp() } just awaits
coEvery { mock.coOp() } answers { 1 } andThenJust awaits
```
See discussion https://github.com/mockk/mockk/discussions/924
> Add `Awaits` extensions similar to `Runs` to await suspend functions until cancelled

- .github/workflows/gradle.yml
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/config/Deps.kt
- gradle.properties
https://kotlinlang.org/docs/whatsnew1720.html
> Upgrade Kotlin to stable 1.7.20 in GitHub workflow

- modules/mockk/src/commonTest/kotlin/io/mockk/it/LambdaTest.kt
There is no test annotation in LambdaTest. Add missing test annotation to LambdaTest.
I don't know history about this, Is there a reason why there is no test annotation?
> Add missing test annotation to LambdaTest

- modules/mockk/src/commonMain/kotlin/io/mockk/impl/verify/UnorderedCallVerifier.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/CaptureSubclassVerificationTest.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/CapturingTest.kt
> Fix verifier logic for slots and different matchers

- modules/mockk/src/commonTest/kotlin/io/mockk/it/SealedClassTest.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/SealedInterfaceTest.kt
- modules/mockk/src/jvmMain/kotlin/io/mockk/impl/recording/JvmSignatureValueGenerator.kt
Fixes #934
There's no specific test for the issue, that is part of this pr: https://github.com/mockk/mockk/pull/937
> Fix InstantiationError when using any() where a sealed type is expected

- README.md
- modules/mockk-dsl/api/mockk-dsl.api
- modules/mockk-dsl/src/commonMain/kotlin/io/mockk/API.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/AdditionalAnswerTest.kt
Hi team! 😬🤓
This is @antonio-manuel and @daniel-dios from @N26!
Since we are testing Kafka ErrorHandlers we wanted to stub a method to return 10 times a given exception and then success with this amazing library 🙌
We are proposing this two new methods to make test even clearer!
Thanks a lot
💓
> Adding throwsMany exception

- README.md
Added note (to spy and coroutines sections) about known issue with suspending functions and spy (issue now nearly two years old)
> Update README.md to include note about 2-year-old 'known issue' for spy and suspend function

- modules/mockk-agent/src/jvmMain/kotlin/io/mockk/proxy/jvm/ProxyMaker.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/SealedClassMockingTest.kt
Fixes #938, fixes #978, fixes #987
> Inline mocked subclass of sealed class along with the sealed class itself

- modules/mockk-agent/src/jvmMain/kotlin/io/mockk/proxy/jvm/transformation/InliningClassTransformer.kt
Fixes #647 by declaring `classBeingRedefined` as a nullable parameter, aligning [JVM's `InliningClassTransformer`](https://github.com/mockk/mockk/blob/master/modules/mockk-agent/src/jvmMain/kotlin/io/mockk/proxy/jvm/transformation/InliningClassTransformer.kt#L67) with [Android's one](https://github.com/mockk/mockk/blob/master/modules/mockk-agent-android/src/main/kotlin/io/mockk/proxy/android/transformation/InliningClassTransformer.kt#L30)
According the [Oracle's documentaiton](https://docs.oracle.com/javase/7/docs/api/java/lang/instrument/ClassFileTransformer.html), it's expected `classBeingRedefined` to be nullable:
> classBeingRedefined - if this is triggered by a redefine or retransform, the class being redefined or retransformed; if this is a class load, null …
> Fixes #647 by allowing `classBeingRedefined` to be `null`

- .github/workflows/gradle.yml
- build.gradle.kts
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/android-application.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/android-library.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/kotlin-jvm.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/kotlin-multiplatform.gradle.kts
* bump Kover to 0.6.1
* apply Kover to all subprojects via buildSrc convention plugins
* enable merged reports
* exclude 'loggerTests' from API validation (unrelated, but a small fix)
> bump Kover to 0.6.1

- .github/workflows/gradle.yml
For instance, instead of the default `tests (11, 1.5.31, true)`, it will render as `[java=11, kotlin=1.5.31, IR=true]`.
> Customize jobs name to make the matrix values more explicit

- modules/mockk/src/commonMain/kotlin/io/mockk/impl/stub/MockKStub.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/impl/stub/MockKStubTest.kt
This PR modifies the way the `MockKException` is constructed when a mock is called with a set of parameters that wasn't configured, so it also adds to the exception message all the answers configured for that mock.
The aim of this change is to help understand why is the mock's call really failing, giving some extra information to the developer.
> Return the configured answers when no answer found

- modules/mockk/src/commonMain/kotlin/io/mockk/impl/verify/UnorderedCallVerifier.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/VerifyAtLeastAtMostExactlyTest.kt
Fix #969
verify atLeast = 0 only passing if the mocked function is called at least once with different parameters
The case in which the method never gets called at all probably just got forgotten in this fix #807
> Recognize atLeast = 0 when mocked methods is never called

- modules/mockk-agent-api/src/jvmMain/kotlin/io/mockk/proxy/common/ProxyMaker.kt
- modules/mockk-agent/src/jvmTest/java/io/mockk/proxy/JvmMockKProxyMakerTest.java
Fix for issue #997 - WeakReference fails when GC is called between `proxy` and `get`, resulting in flaky tests. This PR simulates & solves the issue.
> Issue #997 - Simulate garbage collected proxy

- README.md
Explained how to mock top-level functions. Added a code example using the mockkStatic(KFunction<*>) overload.
> Added the "Top Level functions" section

- modules/mockk/build.gradle.kts
Currently, mockk pulls in SL4J even though it's an optional dependency. This causes a warning as detailed in https://github.com/mockk/mockk/issues/243
With this change, SL4J is changed to a compileOnly dependency which truly makes it optional without having any additional work needed.
> Make slf4j an optional dependency

- modules/mockk/src/jvmMain/kotlin/io/mockk/junit5/MockKExtension.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/junit5/MockKExtensionConstructorBindingTest.kt
One limitation is that constructor field order is important, mock dependencies must go before actual class. In order to remove this limitation we have to ask Junit team for helping hand.
Closes https://github.com/mockk/mockk/issues/758
> Inject mocks via constructor to avoid lateinit var

- buildSrc/src/main/kotlin/buildsrc/config/Deps.kt
Android 14 [requires read-only jar file creation](https://developer.android.com/about/versions/14/behavior-changes-14#safer-dynamic-code-loading), and the latest version of `dexmaker` has this change:
https://github.com/linkedin/dexmaker/blob/main/CHANGELOG.md
https://github.com/linkedin/dexmaker/pull/181
Without this change, trying to mock certain classes on the Android 14 preview emulator results in this error:
```
io.mockk.MockKException: Can't instantiate proxy for class java.util.Date
at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:64)
at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:24)
...
Caused by: io.mockk.proxy.MockKAgentException: Failed to subclass class java.util.Date
at …
```
> Update dexmaker version to 2.28.3 for Android 14 support

- README.md
- modules/mockk-dsl/api/mockk-dsl.api
- modules/mockk-dsl/src/commonMain/kotlin/io/mockk/API.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/ReflectiveMockTests.kt
In transitioning from mockito to mockk, the one feature I've been missing is Mockito's `defaultAnswer` concept. 
It seems like we can actually replicate this concept in mockk using reflection, however we're blocked w/o a way to define an `any()` matcher given a KClass or KType instead of a reified type.
This PR currently adds only the needed `fun any(KClass)` and `fun match(Matcher, KClass)` functions to the api to open up the possibility of mockking via reflection, and avoids trying to define new dsl for declaring default answers. 
We also demonstrate two examples of reflective mockking. In both examples we mock a TestBuilder and tell it to always return itself. This is just to demonstrate the possibilities we'd be opening up with this change.
> Add `fun <T> MockKMatcherScope.any(KClass<T>): T`

- modules/mockk/src/commonMain/kotlin/io/mockk/MockK.kt
Changes `"Cancel"` to `"Clears"` for the `clearStaticMockk` header.
Fixes #1122.
> 1122(docs): fix header for `clearStaticMockk`

- README.md
- modules/mockk-dsl/api/mockk-dsl.api
- modules/mockk-dsl/src/commonMain/kotlin/io/mockk/API.kt
- modules/mockk-dsl/src/commonMain/kotlin/io/mockk/Matchers.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/MockK.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/CapturingTest.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/CapturingSlotTest.kt
Hello,
This is PR for Allow to Capture nullable values with `CapturingSlot` see [293](https://github.com/mockk/mockk/issues/293). Seems it works according to tests.
Changes on  `CapturingSlot` API are big, I can make them less invasive, but currently I don`t know how much problem it is. I mean removal of 
```
public field captured Ljava/lang/Object; //is not field only get/set now
public final fun setCaptured (Z)V // only getter now
public final fun setNull (Z)V // only getter now
```
> Issue 293: support capture nullable with slot

- modules/mockk/src/jvmMain/kotlin/io/mockk/impl/annotations/MockInjector.kt
SSIA
Please see the commit comments for detailed changes.
> Minor performance improvements to MockInjector

- .github/workflows/gradle.yml
As suggested [here](https://github.com/mockk/mockk/pull/1145#issuecomment-1713924755), this updates MockK's Android test targets to be API 29 and 31 (removing 21 and adding 31). The older target is broken and no longer mainstream, while the newer is relatively common.
> Update Android test targets

- .github/workflows/gradle.yml
The last usage was removed in https://github.com/mockk/mockk/commit/ada19d57d42aac1e69007cfbef14f8c5294e0ef8#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7
> Remove Kotlin-IR from CI matrix

- modules/mockk-dsl/src/commonMain/kotlin/io/mockk/API.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/MockK.kt
> Reduce the use of spread operator to improve performance

- .github/workflows/gradle.yml
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/config/Deps.kt
- buildSrc/src/main/kotlin/buildsrc/convention/toolchain-jvm.gradle.kts
- gradle.properties
Fix #1048 
* prefix the Java and Kotlin versions with `io_mockk`, which can help in some situations (e.g. if an individual wants to set them specifically on their machine they can add them in `$GRADLE_USER_HOME/gradle.properties` and not risk clashing with other properties)
* standardise the naming for the Kotlin and Java versions (I chose snake_case, but camelCase would work as well - up to you)
* remove Java version/target/toolchain from `buildSrc/build.gradle.kts` - it should be inherited from the root project
> update Kotlin and Java Toolchain properties, and setting them in CI

- buildSrc/src/main/kotlin/buildsrc/convention/android-library.gradle.kts
`dokkaJavadoc` relies implicitly on `kaptDebugKotlin` and `kaptReleaseKotlin` leading to Gradle failing the build. Adding explicit dependency as the message suggest fixes the issue.
> Fix `dokkaJavadoc` publishing task

- modules/mockk/src/jvmTest/kotlin/io/mockk/it/ParallelTest.kt
Closes #1165
This could also be solved by adding the slf4j/logback dependency to the jvmTest configutation.
Tell me what's the best approach.
> Fix unit tests errors by using `slf4jOrJulLogging()`

- buildSrc/src/main/kotlin/buildsrc/convention/android-library.gradle.kts
It seems like KAPT was never actually used in this project. Building a release with and without KAPT leads to identical binaries.
> Remove KAPT from Android libraries

- buildSrc/src/main/kotlin/buildsrc/config/Deps.kt
[This commit](https://github.com/mockk/mockk/commit/b6cf9551da37b17f718f44677107ea23ec616982) changed JVM source compatibility to JVM 11, but this doesn't seem to be required. Reverting to 1.8 compatibility supports more apps and libraries that target JVM <11.
> JVM 1.8 source compatibility

- buildSrc/src/main/kotlin/buildsrc/convention/android-application.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/android-library.gradle.kts
- modules/mockk-agent-android/build.gradle.kts
- modules/mockk-android/build.gradle.kts
To fix https://github.com/mockk/mockk/issues/1180
The breaking change would not occur because MockK does not use `R` files.
If you have an appropriate namespace specification, please comment.
> Specify unique `android.namespace` to resolve warnings

- README.md
> Add scoped mock documentation

- modules/mockk-agent/src/jvmMain/kotlin/io/mockk/proxy/jvm/transformation/InliningClassTransformer.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/ValueClassTest.kt
(issue #977)
Adds exclusion rule to prevent interception of the value class getValue method
> Fixes infinite recursion when stubbing a fun that returns value class

- build.gradle.kts
Fixes #1191 
Not a particularly nice solution but unfortunately type safe project access doesn't like mentioning non-existing projects at all - which is okay since that's what it was built for.
Afaik there isn't any check whether a constant is defined in Kotlin script, so I had to resort to a more traditional approach... :grimacing:
> Prevent kover setup failure without Android SDK

- modules/mockk-agent/src/jvmMain/kotlin/io/mockk/proxy/jvm/advice/SelfCallEliminator.kt
- modules/mockk-agent/src/jvmTest/java/io/mockk/proxy/advice/SelfCallEliminatorTest.kt
Issue #366 
Modified the `checkOverride` function to include a check for parameter type assignability, preventing infinite recursion and resolving the stack overflow issue.
> Fix StackOverflowError calling method on spy of class with generic base class

- modules/mockk-agent/api/mockk-agent.api
- modules/mockk-agent/src/jvmMain/java/io/mockk/proxy/jvm/advice/jvm/JvmMockKProxyInterceptor.java
- modules/mockk-agent/src/jvmMain/kotlin/io/mockk/proxy/jvm/util/DefaultInterfaceMethodResolver.kt
- modules/mockk-agent/src/jvmTest/java/io/mockk/proxy/util/DefaultInterfaceMethodResolverTest.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/it/CallOriginalOnDefaultInterfaceMethodTest.kt
Issue: #64
The Kotlin compiler generates an additional class that contains an implementation of a default method as a static member. This method will always be intercepted by InterceptNoSuper since it doesn't have a `@SuperCall`.
Reference: 
https://github.com/mockk/mockk/blob/ef56926bbbc740cb0a5ae87a56726c3ca175713e/modules/mockk-agent/src/jvmMain/java/io/mockk/proxy/jvm/advice/jvm/JvmMockKProxyInterceptor.java#L34-L38
To determine whether the method is a default interface method or not, I have implemented a new utility class named DefaultInterfaceMethodResolver. 
This class attempts to find the DefaultImpls class and then the default method.
> Fix callOriginal on default interface method

- modules/mockk-agent/src/jvmMain/kotlin/io/mockk/proxy/jvm/advice/Interceptor.kt
- modules/mockk-core/api/mockk-core.api
- modules/mockk-core/src/commonMain/kotlin/io/mockk/core/ValueClassSupport.kt
- modules/mockk-core/src/jvmMain/kotlin/io/mockk/core/ValueClassSupport.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/ValueClassTest.kt
Fixes issue: https://github.com/mockk/mockk/issues/1037
Without this change, the two new test cases fail with:
```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class io.mockk.it.ValueClassTest$Companion$DummyValue (java.lang.Integer is in module java.base of loader 'bootstrap'; io.mockk.it.ValueClassTest$Companion$DummyValue is in unnamed module of loader 'app')
```
> Only unbox value class answers when appropriate

- modules/mockk-dsl/src/commonMain/kotlin/io/mockk/Matchers.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/ValueClassTest.kt
When using `capture` with a mutable list of a value type (i.e. using `CaptureMatcher`), the wrapped value is captured rather than the value type:
```
expected: <DummyValue(value=101)> but was: <101>
```
_When using `capture` with a `slot` (i.e. using `CapturingSlotMatcher`) this is handled by calling the internal `boxCast` helper function._
Use `boxCast` in `CaptureMatcher `, in the same way as `CapturingSlotMatcher` does.
> Fix capture using mutable list of value class

- doc/md/jdk16-access-exceptions.md
Whilst the documentation added in #965 is excellent, developers using Gradle within an Android project require a standard template that differs from the Gradle example provided.
I recently solved this issue within my own project and struggled to find a "copypastable" solution. Adding this example will make the guide much more useful for other Android developers!
> Updates documentation to include example access error workaround for Android users

- modules/mockk-dsl/src/commonMain/kotlin/io/mockk/API.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/impl/recording/states/StubbingStateTest.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/ConstructorMockTest.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/WasNotCalledTest.kt
@Raibaz Here is to PR the fix https://github.com/mockk/mockk/issues/1155
I used the `internalIsMockKMock` with all parameters to true to check is the `called` object is a mock, please tell me if I miss something.
For the tests, I added some in a separate file, I wasn't sure where to put them.
Closes #1155
> Fix wasNotshould throw exception when called on non mocked object

- modules/mockk-core/src/jvmMain/kotlin/io/mockk/core/ValueClassSupport.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/ValueClassTest.kt
I notice that after bumping the version to 1.13.10, mockk cannot mock a value class type property in a class. 
This can be reproduced by my newly added test case in `modules/mockk/src/commonTest/kotlin/io/mockk/it/ValueClassTest.kt` below. 
stacktrace:
```
java.lang.ClassCastException: class io.mockk.it.ValueClassTest$Companion$DummyValue cannot be cast to class java.lang.Integer (io.mockk.it.ValueClassTest$Companion$DummyValue is in unnamed module of loader 'app'; java.lang.Integer is in module java.base of loader 'bootstrap')
at io.mockk.it.ValueClassTest$Companion$DummyService.getValueClassField-_Hougu0(ValueClassTest.kt:642)
at io.mockk.it.ValueClassTest.field is ValueClass, returns ValueClass(ValueClassTest.kt:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Nati …
```
> Fix cannot mock value class for class property in 1.13.10

- README.md
- modules/mockk-dsl/api/mockk-dsl.api
- modules/mockk-dsl/src/commonMain/kotlin/io/mockk/API.kt
- modules/mockk/api/mockk.api
- modules/mockk/src/commonMain/kotlin/io/mockk/MockK.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/CaptureSubclassVerificationTest.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/CoVerifyTest.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/VerificationErrorsTest.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/VerifyAtLeastAtMostExactlyTest.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/VerifyTest.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/it/VerificationAcknowledgeTest.kt
**this is draft implementation**
i'd like maintainers to check such points
- `API.kt` and `MockK.kt` are implemented appropriately
- tests are enough
- some changes i added as refactoring are acceptable
thank you
___
based on [this discussion](https://github.com/mockk/mockk/discussions/1227), i added `verifyCount` DSL to make verifying call count easy
```
val mock = mockk<ClassUnderTest>()
...
verifyCount {
1 * { mock.method() } // this is same as verify(exactly = 1) { mock.method() }
0 * { mock.method() } // this is same as verify(exactly = 0) { mock.method() }
(0..5) * { mock.method() } // this is same as verify(atLeast = 0, atMost = 5) { mock.method() }
}
```
this is inspired by [Spock](https://spockframework.org/spock/docs/2.3/spock_primer.html#_interactions) and …
> Introduce `verifyCount` DSL

- modules/mockk/api/mockk.api
- modules/mockk/src/jvmMain/kotlin/io/mockk/MockK.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/it/StaticMockkTest.kt
For a class, Mockk allows to:
- `mockkStatic(klass)`
- `unmockkStatic(klass)`
- `clearStaticMock(klass)`
But for static properties and functions, since #518, only the first 2 are supported:
- `mockkStatic(::staticMethod)`
- `unmockkStatic(::staticMethod)`
- `clearStaticMock(::staticMethod)` // Doesn't compile
The helper functions were missing.
> Implement `clearStaticMockk` for KFunction and KProperty

- CONTRIBUTING.md
I opened a PR that didn't pass the CI (#1239) even after reading CONTRIBUTING.md:
> Make sure all tests pass and you have a passing build for the whole project.
I did run `./gradlew test` but the CI runs the superset `./gradlew check`.
How about referencing the exact command to run before submitting the PR at the end of that line:
~~~diff
- 1. Make sure all tests pass and you have a passing build for the whole project.
+ 1. Make sure all tests pass and you have a passing build for the whole project (run `./gradlew check`).
~~~
~It would also be nice to document `./gradlew apiDump` (only found it after manually fixing the API file), but keeping the instructions short is probably better. What do you think?~ It's referenced in the `./gradlew check` error message.
> [CONTRIBUTING.md] Suggest running `gradle check` before opening a PR

- modules/mockk-core/src/jvmMain/kotlin/io/mockk/core/ValueClassSupport.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/ValueClassTest.kt
According to the Kotlin compiler source code, a `suspend` function returning a primitive `value class`:
> Can't unbox into a primitive, since suspend functions have to return a reference type.
See: https://github.com/JetBrains/kotlin/blob/v1.9.24/compiler/ir/backend.jvm/codegen/src/org/jetbrains/kotlin/backend/jvm/codegen/CoroutineCodegen.kt#L108-L110
PS: I hope it's okay that I created a PR directly instead of opening an Issue first, given I already had a fix.
<details>
<summary>Stack trace</summary>
```
class java.lang.Long cannot be cast to class Test$Value (java.lang.Long is in module java.base of loader 'bootstrap'; Test$Value is in unnamed module of loader 'app')
java.lang.ClassCastException: class java.lang.Long cannot be cast to class Test$Value (java.lang.Long is in module …
```
> Don't unbox primitive value class returned by suspend function

- modules/mockk/src/jvmMain/kotlin/io/mockk/junit5/MockKExtension.kt
In MockKExtension, the README.md currently states that if a test is wanted to run in parallel we are able to attach the @RequireParallelTesting annotation. However, that is currently not the case. Looking deeper in MockKExtension, one of the ExtensionContext's is not like the others.
Closes #1261
> Fix RequireParallelTesting Annotation

- modules/mockk-core/src/jvmMain/kotlin/io/mockk/core/ValueClassSupport.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/ValueClassTest.kt
- modules/mockk/src/jvmMain/kotlin/io/mockk/impl/instantiation/JvmMockFactoryHelper.kt
Fix https://github.com/mockk/mockk/issues/813
Problem:
When trying to mock a function that returns a nullable value class, a ClassCastException was thrown. Thats because  mockk is using the boxedClass. Nullable value classes should be handled differently because they are not inlined.
For example
`Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class io.mockk.it.ValueClassTest$Companion$DummyValue (java.lang.Integer is in module java.base of loader 'bootstrap'; io.mockk.it.ValueClassTest$Companion$DummyValue is in unnamed module of loader 'app')`
Implementation:
When the return type of the function or a member property is nullable do not use the boxedClass but use the value class itself
> fix(813): Handle nullable value classes

- modules/mockk/src/commonMain/kotlin/io/mockk/impl/verify/UnorderedCallVerifier.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/VerificationErrorsTest.kt
This PR adds support for the case where `min` and `max` calls counts are the same. Instead of saying `at least <x> and at most <x> calls`, it now displays `exactly <x> calls`.
> Improve error message on unexpected calls count

- modules/mockk-core/src/jvmMain/kotlin/io/mockk/core/ValueClassSupport.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/ValueClassTest.kt
- modules/mockk/src/jvmMain/kotlin/io/mockk/impl/instantiation/JvmMockFactoryHelper.kt
Fix https://github.com/mockk/mockk/issues/1308
Problem:
The [PR](https://github.com/mockk/mockk/pull/1295) introduced a regression when a function is returning a nullable value class with a property that is not primitive and also in cases of a nested value class where the innermost property is not a primitive. In these cases we should be using the boxed value instead of the unboxed value.
Implementation:
The implementation was adjusted based on the following.
- When the innermost property of the value class is primitive then use the unboxed value
- When the innermost property of the value class is NOT primitive then use the boxed value. 
- Added some tests for nested value class as a return type of a suspending functions.
- Revert the change in JvmMockFactoryHelper.kt as it's not …
> fix(1308): Handle nullable complex and nested value classes

- modules/mockk-core/src/jvmMain/kotlin/io/mockk/core/ValueClassSupport.kt
- test-modules/client-tests/src/jvmTest/kotlin/io/mockk/core/DefaultValueInMockedValueClassTest.kt
Fix for the Issue: https://github.com/mockk/mockk/issues/1330 
Fixed for given nested value classes when relaxed mocking is enabled then value successfully verified.
Added couple of test(s) so that it will be verified in every PR.
**Root Cause**
Because of this PR's: https://github.com/mockk/mockk/pull/1314/files change in the below code in the else part, this issue was broken. Instead of returning this in the else block which returns the value class, instead check if there is any boxedValue and return the same if exists else return the same value class.
**Earlier**
```
return if (resultType == expectedReturnType && !(isReturnNullable && isPrimitive)) {
this.boxedValue
} else {
this
}
```
**Now**
```
return if (resultType == expectedReturnType && !(isReturnNullable && isPrimitive)) { …
```
> Fix(Issue no. 1330) for Relaxed Mocking Value When Property is Nested Value Class

- modules/mockk-core/src/jvmMain/kotlin/io/mockk/core/ValueClassSupport.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/ValueClassTest.kt
Fix( Issue #[1073](https://github.com/mockk/mockk/issues/1073)): Bug fix for the issue with mocking value classes with coEvery.
Enable few disabled tests for support nested value classes (issue: [859](https://github.com/mockk/mockk/issues/859))
> Fix( Issue #1073): Bug fix for the issue with mocking value classes with coEvery

- modules/mockk/src/jvmMain/kotlin/io/mockk/junit5/MockKExtension.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/junit5/MockKExtensionRequireParallelTestingTest.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/junit5/MockKExtensionWithoutRequireParallelTestingTest.kt
Fixes https://github.com/mockk/mockk/issues/1329
V1.13.13 added calling unmockkAll() after tests when using the JUnit 5 MockKExtension. It has the same problems with running tests in parallel that happened when the extension was modified to call clearAllMocks() after tests. The call to unmockkAll() is wrapped in a check with `!context.requireParallelTesting` in this PR.
> Fix (issue# 1329) parallel testing for unmockkAll

- README.md
This will avoid the creation of more Issues regarding this topic and save hours to devs trying to mock private fields. See [this comment](https://github.com/mockk/mockk/issues/263#issuecomment-549018282) from Oleksiy which explains this
Current issues about this topic:
- https://github.com/mockk/mockk/issues/1307
- https://github.com/mockk/mockk/issues/1244
- https://github.com/mockk/mockk/issues/1291
- https://github.com/mockk/mockk/issues/1159
- https://github.com/mockk/mockk/issues/1111
- https://github.com/mockk/mockk/issues/1070
- https://github.com/mockk/mockk/issues/866
> Update README.md - Clarify that private fields cannot be mocked

- README.md
- modules/mockk-dsl/api/mockk-dsl.api
- modules/mockk-dsl/src/commonMain/kotlin/io/mockk/MockKSettings.kt
- modules/mockk-dsl/src/jsMain/kotlin/io/mockk/MockKSettings.kt
- modules/mockk-dsl/src/jvmMain/kotlin/io/mockk/MockKSettings.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/impl/recording/states/StubbingAwaitingAnswerState.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/impl/recording/states/StubbingAwaitingAnswerStateTest.kt
Hi,
as mentioned in https://github.com/mockk/mockk/issues/1291, if setting a backing field fails, it just prints a warning but the test does not fail. I introduced a new parameter to alter this behavior - when the new property is set to true, the test fails.
I think this improves handling a lot, as clearly the developer wanted to mock something which failed.
The parameters are a bit confusing to me, as there is the io/mockk/settings.properties and the mockk.properties file. I used settings.properties because it is available in the code I added the fix to. The property "throwExceptionOnBadMock" sounds like it should do what I implemented, but I did not want to break existing codebases by re-using this property.
The unit tests are not very nice, the real problem occurs if you mix Java and …
> Added new property "failOnSetBackingFieldException" to fail test if a backing field could not be set

- modules/mockk-core/src/jvmMain/kotlin/io/mockk/core/ValueClassSupport.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/ValueClassTest.kt
Last version that worked for me with returned `Result` classes was [1.13.9](https://github.com/mockk/mockk/releases/tag/1.13.9). I've checked all the commits that were added between `1.13.1` and `1.13.10` and realized that [this](https://github.com/mockk/mockk/pull/1202/files#diff-257408db2d9e7ef45cb767a310cd6b2e2d98d372d4bcee67618d290c28ce5b37R23) change was responsible for this behavior.
I've reverted changes, at it looks like all tests are passing (even those added in the below PR that was causing issues). I think the change is not needed anymore and can be simply reverted
However I tested it mostly with `Result` class, so alternatively I can change this PR to only include workaround for `Result`:
```kotlin
actual val <T : Any> T.boxedValue: Any?
@Suppress("UNCHECKED_CAST")
get() = if …
```
> Fix returning result values

- modules/mockk-dsl/src/commonMain/kotlin/io/mockk/API.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/it/VerificationAcknowledgeTest.kt
This PR implements the approach discussed in **issue #821**—**resetting recorded calls between test cases** to ensure test isolation without affecting shared mocks.  
- Updated `internalConfirmVerified` to **reset recorded calls** while keeping shared mocks intact.  
- Used `ClearOptions(recordedCalls = true, verificationMarks = true, …)` to ensure test isolation **without affecting persistent mocks**.  
- Performed some **refactoring** to improve code clarity—please let me know if these changes are acceptable.  
This test fails under the new behavior because it expects **manually cleared verification marks** to be considered.  
The new approach **prevents clearing unless explicitly requested**, causing this assertion to fail:  
```kotlin
@Test
fun clearMarks() {
every { mock.op(1) } …
```
> fix: ensure confirmVerified is isolated per test

- README.md
Do not recommend users to change (and ship!) test configuration in their production builds.
> Change mockk configuration paths to test sourceSet

- buildSrc/src/main/kotlin/buildsrc/config/Deps.kt
Bump byte buddy version to 1.17.5, to support java 24
Related issue: #1386
> chore: bump byte buddy version to support java 24

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/config/Deps.kt
- modules/mockk/src/commonTest/kotlin/io/mockk/it/CoJustAwaitTest.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/junit5/MockKExtensionRequireParallelTestingTest.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/junit5/MockKExtensionWithoutRequireParallelTestingTest.kt
Bump versions:
dokka: 2.0.0
kotlinx.coroutines: 1.10.1
slf4j: 2.0.17
logback: 1.5.18
junit jupiter: 5.12.2
> chore: bump dokka, kotlinx.coroutines, slf4j, logback, junit jupiter

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/config/Deps.kt
- buildSrc/src/main/kotlin/buildsrc/convention/android-application.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/android-library.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/kotlin-jvm.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/kotlin-multiplatform.gradle.kts
- buildSrc/src/main/kotlin/buildsrc/convention/toolchain-jvm.gradle.kts
- modules/mockk-agent/build.gradle.kts
- modules/mockk/build.gradle.kts
- test-modules/client-tests/build.gradle.kts
- test-modules/logger-tests/build.gradle.kts
Bump kotlin version to 2.1.20
Bump com.android.tools.build:gradle to 8.9.2
Bump org.jetbrains.kotlinx:binary-compatibility-validator to 0.17.0
Breaking Change: Minimal Kotlin API version for 2.1.20 is 1.6
> chore: bump kotlin to 2.1.20

- modules/mockk-dsl/src/commonMain/kotlin/io/mockk/API.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/it/VerificationAcknowledgeTest.kt
fixes #242
When a static class is mocked using the mockStatic method, its javaClass is used as the key in the stubRepo. 
To make use of this, add logic to convert a given KClass to its javaClass and use it in the when clause.
> fix: enable confirmVerified to work with static mocks

- modules/mockk-dsl/api/mockk-dsl.api
- modules/mockk-dsl/src/commonMain/kotlin/io/mockk/API.kt
- modules/mockk-dsl/src/commonMain/kotlin/io/mockk/Matchers.kt
One more fix for #707
Previous fix (#776) was reverted (https://github.com/mockk/mockk/issues/707#issuecomment-1056006754), but this one should not repeat the same error.
I use the same idea as in mockito-kotlin `check`: https://github.com/mockito/mockito-kotlin/blob/main/mockito-kotlin/src/main/kotlin/org/mockito/kotlin/Verification.kt#L285
It is not ideal, as it may print assertion errors even on verify pass (in case on many invocations), but this is how mockit-kotlin `check` works too. And I think this is better than nothing
> Add logging on failure inside withArg

- README.md
- modules/mockk-bdd-android/build.gradle.kts
- modules/mockk-bdd-android/src/androidTest/kotlin/io/mockk/bdd/BDDAndroidTest.kt
- modules/mockk-bdd-android/src/main/AndroidManifest.xml
- modules/mockk-bdd-android/src/main/kotlin/io/mockk/bdd/BDDAndroid.kt
- modules/mockk-bdd/api/mockk-bdd.api
- modules/mockk-bdd/build.gradle.kts
- modules/mockk-bdd/src/commonMain/kotlin/io/mockk/bdd/BDD.kt
- modules/mockk-bdd/src/jvmTest/kotlin/io/mockk/bdd/BDDTest.kt
- settings.gradle.kts
Implement BDD style aliases as separate modules
This PR implements BDD (Behavior-Driven Development) style API for MockK as proposed in issue #439. The implementation provides aliases for existing MockK functions with BDD-oriented naming
- `given` (alias for `every`)
- `coGiven` (alias for `coEvery`)
- `then` (alias for `verify`)
- `coThen` (alias for `coVerify`)
Following discussions in PR #662, these aliases are implemented as separate modules to avoid confusion and maintain code consistency.
- **mockk-bdd**: Base module with BDD style aliases
- **mockk-bdd-android**: Android-specific module (but... just wrapping mockk-bdd 😂)
**Separate Modules**: As suggested in PR #662 discussion, BDD aliases are implemented as separate modules to
- Avoid confusion with existing APIs
- Allow teams to …
> [Feature] Implement BDD-style aliases as separate module (mockk-bdd)

- buildSrc/src/main/kotlin/buildsrc/config/Deps.kt
Downgrade `net.bytebuddy.byte-buddy` to 1.5.11 to be compatible with current android build instrumentation.
Should fix issues:
#1406 
#1408 
But it is still compatible with Java 24 (https://github.com/mockk/mockk/pull/1387)
> fix: downgrade byte-buddy to 1.5.11

- modules/mockk/src/commonMain/kotlin/io/mockk/impl/recording/SignatureMatcherDetector.kt
- modules/mockk/src/commonMain/kotlin/io/mockk/impl/recording/states/StubbingState.kt
- modules/mockk/src/jvmMain/kotlin/io/mockk/impl/instantiation/JvmMockFactoryHelper.kt
- modules/mockk/src/jvmTest/kotlin/io/mockk/it/InlineMemberFunctionFailFastTest.kt
Fixes #1030 : "Throwing a descriptive error upon encountering inline function"
Kotlin `inline` functions are inlined at the call site, meaning their actual method calls disappear at runtime.
As a result, proxy-based mocking is fundamentally impossible.
Previously, attempts to mock inline functions would fail with vague messages like:
`"Failed matching mocking signature..."` or `"Missing mocked calls..."`, making it difficult to debug.
This change classifies such failures into two clear categories and provides more actionable feedback:
1. Interceptable environment (proxy created)
- Detects inline functions in JvmMockFactoryHelper and immediately throws a MockKException
- Message: Mocking Kotlin inline functions is not supported
2. Non-interceptable environment (no proxy created)
- When no …
> add fail-fast guard for Kotlin inline function mocking (#1030)
